name: Node lint and Test
run-name: Use lint and Test nodejs app
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Configurar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalar dependencias
        working-directory: ./calculadora
        run: |
          npm ci
      - name: Ejecutar lint
        working-directory: ./calculadora
        run: |
          npm run lint
      - name: Ejecutar Test
        working-directory: ./calculadora
        run: |
          npm run test